apiVersion: bundle.gravitational.io/v2
kind: Bundle
metadata:
  name: telekube
  resourceVersion: "0.0.0"
  description: |
    Base cluster image with Kubernetes v${GRAVITY_K8S_VERSION}
endpoints:
  - name: "Gravity Control Panel"
    description: |
      Local administrative user interface of this Gravity cluster
    selector:
      app: gravity-site
    protocol: https
  - name: "Bandwagon"
    hidden: true
    serviceName: bandwagon
providers:
  aws:
    regions:
      # the current version of gravitational/provisioner supports
      # only us-east-2 region for some reason
      - us-east-2
installer:
  setupEndpoints:
    - "Bandwagon"
  flavors:
    prompt: "Select a flavor"
    default: "one"
    items:
      # as of the time of this writing, gravitational/provisioner
      # supports only nodes with role 'node' so all other flavors
      # have been removed
      #
      # we can bring flavors with 'knode' and 'master' roles back
      # if/when provisioner becomes more flexible
      - name: "one"
        description: "1 node"
        nodes:
          - profile: node
            count: 1
      - name: "two"
        description: "2 nodes"
        nodes:
          - profile: node
            count: 2
      - name: "three"
        description: "3 nodes"
        nodes:
          - profile: node
            count: 3
nodeProfiles:
  - name: node
    description: "Gravity Auto Node"
    requirements:
      cpu:
        min: 1
      ram:
        min: "2GB"
      os:
        - name: centos
          versions: ["7", "8"]
        - name: rhel
          versions: ["7", "8"]
        - name: ubuntu
          versions: ["16.04", "18.04", "20"]
        - name: debian
          versions: ["8", "9", "10"]
      volumes:
        - path: /var/lib/gravity
          capacity: "10GB"
          filesystems: ["xfs", "ext4"]
  - name: knode
    description: "Gravity Node"
    labels:
      node-role.kubernetes.io/node: "true"
    requirements:
      cpu:
        min: 1
      ram:
        min: "2GB"
      os:
        - name: centos
          versions: ["7", "8"]
        - name: rhel
          versions: ["7", "8"]
        - name: ubuntu
          versions: ["16.04", "18.04", "20"]
        - name: debian
          versions: ["8", "9", "10"]
      volumes:
        - path: /var/lib/gravity
          capacity: "10GB"
          filesystems: ["xfs", "ext4"]
  - name: master
    description: "Gravity Master"
    taints:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
    labels:
      node-role.kubernetes.io/master: "true"
    requirements:
      cpu:
        min: 1
      ram:
        min: "2GB"
      os:
        - name: centos
          versions: ["7", "8"]
        - name: rhel
          versions: ["7", "8"]
        - name: ubuntu
          versions: ["16.04", "18.04", "20"]
        - name: debian
          versions: ["8", "9", "10"]
      volumes:
        - path: /var/lib/gravity
          capacity: "10GB"
          filesystems: ["xfs", "ext4"]
  - name: gmaster
    description: "Gravity Master (not kubernetes master)"
    taints:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
    labels:
      gravitational.io/k8s-role: "master"
hooks:
  clusterProvision:
    job: file://clusterProvision.yaml
  nodesProvision:
    job: file://nodesProvision.yaml
  nodesDeprovision:
    job: file://nodesDeprovision.yaml
  clusterDeprovision:
    job: file://clusterDeprovision.yaml
  preUpdate:
    job: file://preUpdate.yaml
storage:
  openebs:
    enabled: false
systemOptions:
  runtime:
    # TODO(dima): test runtime
    version: "20.0.0-rc1"
  docker:
    storageDriver: overlay2
extensions:
  logs:
    disabled: true
  monitoring:
    disabled: true
  catalog:
    disabled: true
